import {today,addDays,dates,schedule,active,record,status,weekly,visible,validateDB,saveTask,setProgress,validDate,combinedSettings,migrateDB,classify,compareTasks} from './core.js?v=2';
const KEY='hibi-todo-v1', $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db={version:1,tasks:[],records:{}},selected=today(),tab='today',editing=null,deleting=null,blocked=false,timer;
function error(message){$('#error').textContent=message;$('#error').hidden=false;}
try{const raw=localStorage.getItem(KEY);if(raw)db=migrateDB(validateDB(JSON.parse(raw)),today());}catch(e){blocked=true;error('保存データを読み込めませんでした。データを保護するため変更を停止しています。ブラウザの保存設定を確認して再読み込みしてください。');}
function commit(fn){if(blocked)throw Error('保存データを読み込めないため変更できません。');const next=structuredClone(db);fn(next);try{localStorage.setItem(KEY,JSON.stringify(next));}catch(e){error('保存できませんでした。ブラウザの空き容量・保存設定を確認してください。入力内容はこの画面に残っています。');throw Error('保存できませんでした。もう一度お試しください。');}db=next;$('#error').hidden=true;render();}
function toast(text){clearTimeout(timer);$('#toast').textContent=text;$('#toast').classList.add('show');timer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
const freq=v=>v.kind==='combined'?`${v.intervalDays}日に1回・週${v.weeklyCount}回`:v.kind==='weekly'?`週${v.n}回`:`${v.n}日に1回`;
const fmt=d=>new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short',timeZone:'UTC'}).format(new Date(d+'T00:00:00Z'));
const short=d=>`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}`;
function empty(title,body,action=false){return `<div class="empty"><div class="empty-icon">✓</div><h2>${title}</h2><p>${body}</p>${action?'<button class="primary" data-action="add">＋ タスクを追加</button>':''}</div>`;}
function row(t,d,manage=false){const r=record(db,t.id,d),v=schedule(t,d)||t.versions.at(-1),s=status(db,t.id,d),priority=classify(db,t,d),label={todo:'未完了',doing:'進行中',done:'完了'}[s],name=manage?v.name:r?.name||v.name;return `<article class="task ${manage?'':s} ${!manage&&priority.level==='optional'?'optional':''}">${manage?'':`<button class="check ${s}" data-action="toggle" data-id="${t.id}" data-date="${d}" aria-label="${esc(name)}を${s==='done'?'未完了':'完了'}にする" aria-pressed="${s==='done'}">${s==='done'?'✓':s==='doing'?'−':''}</button>`}<div class="task-main"><p class="task-title">${esc(name)}</p><div class="meta"><span class="badge">${freq(manage?v:r||v)}</span>${manage?`<span>${short(v.start)} 開始${v.start>today()?'・開始前':''}</span>`:v.kind==='combined'?`<span class="priority-label ${priority.level}">${priority.level==='required'?'必須':priority.level==='optional'?'週目標のための候補':''}</span><span>今週 ${weekly(db,t,d).done} / ${v.weeklyCount}回</span>`:v.kind==='weekly'?`<span>今週 ${weekly(db,t,d).done} / ${v.n}回</span>`:''}</div></div>${manage?`<div class="task-actions"><button data-action="edit" data-id="${t.id}" aria-label="${esc(name)}を編集">編集</button><button data-action="delete" data-id="${t.id}" aria-label="${esc(name)}を削除">削除</button></div>`:`<button class="progress-btn ${s}" data-action="cycle" data-id="${t.id}" data-date="${d}" aria-label="${esc(name)}の進捗：${label}。クリックで切り替え">${label}</button>`}</article>`;}
function render(){ $('#date').value=selected;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false');});let html='';
if(tab==='today'){const tasks=db.tasks.filter(t=>visible(db,t,selected));const done=tasks.filter(t=>status(db,t.id,selected)==='done').length;html=`<div class="summary"><div><h2>${selected===today()?'今日のタスク':fmt(selected)}</h2><p>${tasks.length?done===tasks.length?'すべて完了。おつかれさまでした。':`あと${tasks.length-done}件、ひとつずつ。`:'今日のペースをつくろう。'}</p></div><div class="count">${done}<small> / ${tasks.length}</small></div></div>`;html+=tasks.length?tasks.sort((a,b)=>compareTasks(db,selected,a,b)).map(t=>row(t,selected)).join(''):db.tasks.some(t=>!t.deletedFrom)?empty('この日のタスクはありません','次の予定まで、ひと休み。'):empty('最初のタスクを登録しよう','続けたいことを、ひとつから。',true);}
if(tab==='tasks'){const tasks=db.tasks.filter(t=>!t.deletedFrom);html=`<p class="list-caption">登録中のタスク ${tasks.length}件</p>`+(tasks.length?tasks.map(t=>row(t,today(),true)).join(''):empty('タスクはまだありません','名前と頻度を決めてはじめよう。',true));}
if(tab==='history'){const rs=Object.values(db.records).filter(r=>r.date<=selected).sort((a,b)=>b.date.localeCompare(a.date));let last='';html=`<p class="list-caption">${fmt(selected)}までの記録</p>`;for(const r of rs){if(last!==r.date){html+=`<h2 class="history-heading"><button class="history-date" data-action="date" data-date="${r.date}">${fmt(r.date)}</button></h2>`;last=r.date;}const t=db.tasks.find(t=>t.id===r.taskId);if(t)html+=row(t,r.date);}if(!rs.length)html+=empty('履歴はまだありません','進捗をチェックすると、ここに残ります。');}
$('#content').innerHTML=html;const ds=dates(selected);$('#week-range').textContent=`${short(ds[0])} – ${short(ds[6])}`;$('#week-days').innerHTML=ds.map((d,i)=>`<button class="day ${d===selected?'selected':''} ${Object.values(db.records).some(r=>r.date===d&&r.status==='done')?'has-done':''}" data-action="date" data-date="${d}" aria-label="${fmt(d)}" ${d===selected?'aria-current="date"':''}><span>${'月火水木金土日'[i]}</span><b>${Number(d.slice(8))}</b><i></i></button>`).join('');const weekTasks=db.tasks.filter(t=>ds.some(d=>active(t,d)||record(db,t.id,d)));$('#week-progress').innerHTML=weekTasks.length?weekTasks.map(t=>{const w=weekly(db,t,selected),v=schedule(t,selected)||t.versions.at(-1);return `<div class="week-item"><p><strong>${esc(v.name)}</strong><span>${w.done} / ${w.target}回</span></p><div class="bar" role="progressbar" aria-label="${esc(v.name)}の週の達成率" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${w.target?Math.min(100,Math.round(w.done/w.target*100)):0}"><i style="width:${w.target?Math.min(100,w.done/w.target*100):0}%"></i></div></div>`;}).join(''):'<p class="muted">登録したタスクの達成状況が表示されます。</p>';}
function openEditor(id=null){editing=id;$('#task-form').reset();$('#form-error').textContent='';$('#modal-title').textContent=id?'タスクを編集':'タスクを追加';$('#edit-note').hidden=!id;const t=db.tasks.find(t=>t.id===id),v=t?(schedule(t,today())||t.versions.at(-1)):null;const settings=v?combinedSettings(v):{intervalDays:1,weeklyCount:7};$('#name').value=v?.name||'';$('#interval-days').value=settings.intervalDays;$('#weekly-count').value=settings.weeklyCount;$('#start').value=v?.start||selected;$('#editor').showModal();$('#name').focus();}
$('#add').onclick=()=>openEditor();$('#close').onclick=()=>$('#editor').close();
$('#task-form').onsubmit=e=>{e.preventDefault();try{commit(next=>saveTask(next,editing,{name:$('#name').value,kind:'combined',intervalDays:Number($('#interval-days').value),weeklyCount:Number($('#weekly-count').value),start:$('#start').value},today()));$('#editor').close();toast(editing?'タスクを更新しました':'タスクを追加しました');}catch(e){$('#form-error').textContent=e.message;}};
function go(d){if(!validDate(d))return;selected=d;render();}
$('#date').onchange=e=>go(e.target.value);$('#prev').onclick=()=>go(addDays(selected,-1));$('#next').onclick=()=>go(addDays(selected,1));$('#today').onclick=()=>go(today());document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action,id,date}=b.dataset;try{if(action==='add')openEditor();if(action==='edit')openEditor(id);if(action==='date'){tab='today';go(date);}if(action==='toggle'||action==='cycle'){const s=status(db,id,date),next=action==='toggle'?(s==='done'?'todo':'done'):({todo:'doing',doing:'done',done:'todo'}[s]);commit(db=>setProgress(db,id,date,next));}if(action==='delete'){deleting=id;$('#delete-name').textContent=(schedule(db.tasks.find(t=>t.id===id),today())||db.tasks.find(t=>t.id===id).versions.at(-1)).name;$('#delete-dialog').showModal();}}catch(e){error(e.message);}});
$('#cancel-delete').onclick=()=>$('#delete-dialog').close();$('#confirm-delete').onclick=()=>{try{commit(db=>{db.tasks.find(t=>t.id===deleting).deletedFrom=today();});$('#delete-dialog').close();toast('タスクを削除しました');}catch(e){error(e.message);}};
window.addEventListener('storage',e=>{if(e.key!==KEY)return;try{db=e.newValue?migrateDB(validateDB(JSON.parse(e.newValue)),today()):{version:1,tasks:[],records:{}};blocked=false;render();}catch{blocked=true;error('別の画面で保存データが変更されました。再読み込みしてください。');}});
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_daily_tasks',description:'指定日のタスクと進捗を取得します。',inputSchema:{type:'object',properties:{date:{type:'string',description:'YYYY-MM-DD'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!validDate(input?.date))throw Error('日付が不正です。');return {date:input.date,tasks:db.tasks.filter(t=>visible(db,t,input.date)).map(t=>({id:t.id,name:record(db,t.id,input.date)?.name||schedule(t,input.date)?.name,status:status(db,t.id,input.date)}))};}})).catch(()=>{});}catch{}}

