import {today,addDays,dates,schedule,active,record,status,weekly,visible,validateDB,saveTask,setProgress,validDate,combinedSettings,migrateDB,classify,compareTasks} from './core.js?v=5';
const KEY='hibi-todo-v1',$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const views=['today','tasks','progress','history'];let db={version:1,tasks:[],records:{}},selected=today(),tab=views.includes(location.hash.slice(1))?location.hash.slice(1):'today',page=0,editing=null,deleting=null,blocked=false,timer;
function error(message){$('#error').textContent=message;$('#error').hidden=false;}
try{const raw=localStorage.getItem(KEY);if(raw)db=migrateDB(validateDB(JSON.parse(raw)),today());}catch{blocked=true;error('保存データを読み込めませんでした。データを保護するため変更を停止しています。再読み込みしてください。');}
function commit(fn){if(blocked)throw Error('保存データを読み込めないため変更できません。');const next=structuredClone(db);fn(next);try{localStorage.setItem(KEY,JSON.stringify(next));}catch{error('保存できませんでした。ブラウザの保存設定を確認してください。');throw Error('保存できませんでした。入力内容は残っています。');}db=next;$('#error').hidden=true;render();}
function toast(s){clearTimeout(timer);$('#toast').textContent=s;$('#toast').classList.add('show');timer=setTimeout(()=>$('#toast').classList.remove('show'),2000);}
const fmt=d=>new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short',timeZone:'UTC'}).format(new Date(d+'T00:00:00Z')),short=d=>`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}`;
function frequency(v){if(v.kind==='deadline')return `${short(v.date||v.scheduledDate)} まで`;if(v.kind==='ondate')return `${short(v.date||v.scheduledDate)} に実施`;if(v.kind==='combined')return [v.intervalDays?`${v.intervalDays}日に1回`:'',v.weeklyCount?`週${v.weeklyCount}回`:''].filter(Boolean).join('・')||'頻度なし';return v.kind==='weekly'?`週${v.n}回`:`${v.n}日に1回`;}
function empty(title,add=false){return `<div class="empty"><h2>${title}</h2>${add?'<p><button class="primary" data-action="add">＋ タスクを追加</button></p>':''}</div>`;}
function row(t,d,manage=false){const r=record(db,t.id,d),v=schedule(t,d)||t.versions.at(-1),s=status(db,t.id,d),priority=classify(db,t,d),name=manage?v.name:r?.name||v.name,label={todo:'未完了',doing:'進行中',done:'完了'}[s];return `<article class="task ${manage?'':s} ${!manage&&priority.level==='optional'?'optional':''}">${manage?'':`<button class="check ${s}" data-action="toggle" data-id="${esc(t.id)}" data-date="${d}" aria-label="${esc(name)}を${s==='done'?'未完了':'完了'}にする" aria-pressed="${s==='done'}">${s==='done'?'✓':s==='doing'?'−':''}</button>`}<div class="task-main"><p class="task-title" title="${esc(name)}">${esc(name)}</p>${manage?`<div class="meta"><span class="badge">${frequency(v)}</span></div>`:''}</div>${manage?`<div class="task-actions"><button data-action="edit" data-id="${esc(t.id)}" aria-label="${esc(name)}を編集">編集</button><button data-action="delete" data-id="${esc(t.id)}" aria-label="${esc(name)}を削除">削除</button></div>`:`<button class="progress-btn ${s}" data-action="cycle" data-id="${esc(t.id)}" data-date="${d}" title="${label}" aria-label="${esc(name)}の進捗：${label}。クリックで切り替え">${s==='doing'?'◐':s==='done'?'✓':'○'}</button>`}</article>`;}
function paged(tasks){const available=$('#content').clientHeight;const size=Math.max(1,Math.floor(available/66));const max=Math.max(1,Math.ceil(tasks.length/size));page=Math.min(Math.max(0,page),max-1);$('#pagination').innerHTML=max>1?`<button data-action="page-prev" aria-label="前のページ" ${page===0?'disabled':''}>‹</button><span>${page+1} / ${max}</span><button data-action="page-next" aria-label="次のページ" ${page===max-1?'disabled':''}>›</button>`:'';return tasks.slice(page*size,(page+1)*size);}
function render(){ $('#date').value=selected;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false');});$('#content').classList.toggle('home',tab==='today');$('#pagination').innerHTML=tab==='today'?'<span></span>':'';let html='';
if(tab==='today'){const tasks=db.tasks.filter(t=>visible(db,t,selected)).sort((a,b)=>compareTasks(db,selected,a,b));html=tasks.length?paged(tasks).map(t=>row(t,selected)).join(''):empty('この日のタスクはありません',!db.tasks.some(t=>!t.deletedFrom));}
if(tab==='tasks'){const tasks=db.tasks.filter(t=>!t.deletedFrom);html=tasks.length?tasks.map(t=>row(t,today(),true)).join(''):empty('タスクはまだありません',true);}
if(tab==='history'){const rs=Object.values(db.records).filter(r=>r.date<=selected).sort((a,b)=>b.date.localeCompare(a.date));let last='';for(const r of rs){if(last!==r.date){html+=`<h2 class="history-heading"><button class="history-date" data-action="date" data-date="${r.date}">${fmt(r.date)}</button></h2>`;last=r.date;}const t=db.tasks.find(t=>t.id===r.taskId);if(t)html+=row(t,r.date);}if(!rs.length)html=empty('履歴はまだありません');}
if(tab==='progress'){const ds=dates(selected);const weekTasks=db.tasks.filter(t=>ds.some(d=>active(t,d)||record(db,t.id,d)));html=`<section class="week-card"><div class="section-head"><h2>週の達成状況</h2><span>${short(ds[0])} – ${short(ds[6])}</span></div><div id="week-days">${ds.map((d,i)=>`<button class="day ${d===selected?'selected':''} ${Object.values(db.records).some(r=>r.date===d&&r.status==='done')?'has-done':''}" data-action="progress-date" data-date="${d}" aria-label="${fmt(d)}"><span>${'月火水木金土日'[i]}</span><b>${Number(d.slice(8))}</b><i></i></button>`).join('')}</div><div id="week-progress">${weekTasks.length?weekTasks.map(t=>{const w=weekly(db,t,selected),v=schedule(t,selected)||t.versions.at(-1);return `<div class="week-item"><p><strong>${esc(v.name)}</strong><span>${w.target?`${w.done} / ${w.target}回`:`${w.done}回完了`}</span></p><div class="bar"><i style="width:${w.target?Math.min(100,w.done/w.target*100):w.done?100:0}%"></i></div></div>`;}).join(''):'<p class="muted">記録はまだありません。</p>'}</div></section>`;}
$('#content').innerHTML=html;}
$('#interval-days').innerHTML='<option value="">設定しない</option>'+Array.from({length:7},(_,i)=>`<option value="${i+1}">${i+1}日に1回</option>`).join('');$('#weekly-count').innerHTML='<option value="">設定しない</option>'+Array.from({length:7},(_,i)=>`<option value="${i+1}">週${i+1}回</option>`).join('');
function updateKind(){const kind=$('#task-kind').value,routine=kind==='combined';$('#routine-fields').hidden=!routine;$('#scheduled-field').hidden=routine;$('#scheduled-label').textContent=kind==='deadline'?'期限':'実施日';$('#start').required=routine;$('#scheduled-date').required=!routine;}
function openEditor(id=null){editing=id;$('#task-form').reset();$('#form-error').textContent='';$('#modal-title').textContent=id?'タスクを編集':'タスクを追加';$('#edit-note').hidden=!id;const t=db.tasks.find(t=>t.id===id),v=t?(schedule(t,today())||t.versions.at(-1)):null;const settings=v&&['combined','interval','weekly'].includes(v.kind)?combinedSettings(v):{intervalDays:1,weeklyCount:null};$('#name').value=v?.name||'';$('#task-kind').value=v&&['deadline','ondate'].includes(v.kind)?v.kind:'combined';$('#interval-days').value=settings.intervalDays?Math.min(7,settings.intervalDays):'';$('#weekly-count').value=settings.weeklyCount||'';$('#start').value=v?.start||selected;$('#scheduled-date').value=v?.date||selected;updateKind();lockEditor();$('#editor').showModal();if(!matchMedia('(pointer:coarse)').matches)$('#name').focus();}
let savedScroll=0;
function lockEditor(){savedScroll=window.scrollY;document.documentElement.style.setProperty('--editor-max-height',Math.max(260,window.innerHeight-24)+'px');document.documentElement.style.setProperty('--locked-page-height',window.innerHeight+'px');document.body.style.top=-savedScroll+'px';document.body.classList.add('modal-open');}
$('#editor').addEventListener('close',()=>{document.body.classList.remove('modal-open');document.body.style.top='';document.documentElement.style.removeProperty('--locked-page-height');window.scrollTo(0,savedScroll);render();});
$('#add').onclick=()=>openEditor();$('#close').onclick=()=>$('#editor').close();$('#task-kind').onchange=updateKind;
$('#task-form').onsubmit=e=>{e.preventDefault();try{const kind=$('#task-kind').value,previous=editing?db.tasks.find(t=>t.id===editing):null,v=previous?(schedule(previous,today())||previous.versions.at(-1)):null;const input=kind==='combined'?{name:$('#name').value,kind,intervalDays:$('#interval-days').value?Number($('#interval-days').value):null,weeklyCount:$('#weekly-count').value?Number($('#weekly-count').value):null,start:$('#start').value}:{name:$('#name').value,kind,date:$('#scheduled-date').value,start:kind==='ondate'?$('#scheduled-date').value:v&&v.kind===kind?v.start:today()};commit(next=>saveTask(next,editing,input,today()));$('#editor').close();toast(editing?'タスクを更新しました':'タスクを追加しました');}catch(e){$('#form-error').textContent=e.message;}};
function go(d){if(!validDate(d))return;selected=d;page=0;render();}function setView(view){tab=view;page=0;history.replaceState(null,'','#'+view);render();$('#content').scrollTop=0;}
$('#date').onchange=e=>go(e.target.value);$('#prev').onclick=()=>go(addDays(selected,-1));$('#next').onclick=()=>go(addDays(selected,1));$('#today').onclick=()=>go(today());document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setView(b.dataset.tab));window.addEventListener('hashchange',()=>setView(views.includes(location.hash.slice(1))?location.hash.slice(1):'today'));
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action,id,date}=b.dataset;try{if(action==='add')openEditor();if(action==='edit')openEditor(id);if(action==='date'){setView('today');go(date);}if(action==='progress-date')go(date);if(action==='page-prev'){page--;render();}if(action==='page-next'){page++;render();}if(action==='toggle'||action==='cycle'){const s=status(db,id,date),next=action==='toggle'?(s==='done'?'todo':'done'):({todo:'doing',doing:'done',done:'todo'}[s]);commit(db=>setProgress(db,id,date,next));}if(action==='delete'){deleting=id;const t=db.tasks.find(t=>t.id===id);$('#delete-name').textContent=(schedule(t,today())||t.versions.at(-1)).name;$('#delete-dialog').showModal();}}catch(e){error(e.message);}});
$('#cancel-delete').onclick=()=>$('#delete-dialog').close();$('#confirm-delete').onclick=()=>{try{commit(db=>{db.tasks.find(t=>t.id===deleting).deletedFrom=today();});$('#delete-dialog').close();toast('タスクを削除しました');}catch(e){error(e.message);}};
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!$('#editor').open)render();},120);});window.addEventListener('storage',e=>{if(e.key!==KEY)return;try{db=e.newValue?migrateDB(validateDB(JSON.parse(e.newValue)),today()):{version:1,tasks:[],records:{}};blocked=false;render();}catch{blocked=true;error('保存データが変更されました。再読み込みしてください。');}});
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_daily_tasks',description:'指定日のタスクと進捗を取得します。',inputSchema:{type:'object',properties:{date:{type:'string'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!validDate(input?.date))throw Error('日付が不正です。');return {date:input.date,tasks:db.tasks.filter(t=>visible(db,t,input.date)).map(t=>({id:t.id,name:record(db,t.id,input.date)?.name||schedule(t,input.date)?.name,status:status(db,t.id,input.date)}))};}})).catch(()=>{});}catch{}}
